export const dummyList = [
  {
    item_id: 1,
    item_img: process.env.PUBLIC_URL + `/image/lip.jpg`,
    item_detail: "LIP",
    item_name: "빨간 립스틱",
    item_price: 49000,
    item_sale: 0,
    item_ordernum: 2334865424,
  },
  {
    item_id: 2,
    item_img: process.env.PUBLIC_URL + `/image/glass.jpg`,
    item_detail: "SKINCEAR",
    item_name: "마스크팩",
    item_price: 4000,
    item_sale: 20,
    item_ordernum: 2873483524,
  },
  {
    item_id: 3,
    item_img: process.env.PUBLIC_URL + `/image/dummy.jpg`,
    item_detail: "FACEMACKUP",
    item_name: "쿠션팩트",
    item_price: 89000,
    item_sale: 33,
    item_ordernum: 5735557357,
  },
  {
    item_id: 4,
    item_img: process.env.PUBLIC_URL + `/image/ampoule.jpg`,
    item_detail: "SKINCEAR",
    item_name: "로션",
    item_price: 39000,
    item_sale: 20,
    item_ordernum: 2033590224,
  },
  {
    item_id: 5,
    item_img: process.env.PUBLIC_URL + `/image/tint.jpg`,
    item_detail: "LIP",
    item_name: "틴트",
    item_price: 49000,
    item_sale: 20,
    item_ordernum: 9826340254,
  },
];
